name: "CI-CD"

on:
  push:
    branches:
      - main

jobs:
  setup-backend:
    name: Setup and Start Backend
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      - name: Install backend dependencies
        run: npm ci
        working-directory: backend

      - name: Seed database
        run: npm run seed
        working-directory: backend

      - name: Start backend
        run: |
          pm2 start "npm run start" --name="Backend"
          echo "Waiting for backend to be ready..."
          while ! nc -z localhost 8000; do
            echo "Backend is not ready yet. Retrying in 5 seconds..."
            sleep 5
          done
          echo "Backend is up and running!"
          shell: bash
        working-directory: backend

  setup-frontend:
    name: Build and Start Frontend
    needs: setup-backend
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Build frontend (Next.js)
        run: npm run build
        working-directory: frontend

      - name: Start frontend
        run: |
          pm2 start "npm run start" --name="Frontend"
          echo "Waiting for frontend to be ready..."
          while ! nc -z localhost 3000; do
            echo "Frontend is not ready yet. Retrying in 5 seconds..."
            sleep 5
          done
          echo "Frontend is up and running!"
          shell: bash
        working-directory: frontend
