name: "CI-CD"

on:
  push:
    branches:
      - main

jobs:
  backend-setup:
    name: Backend Setup
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      - name: Install backend dependencies
        run: |
          npm install
        working-directory: backend

  frontend-setup:
    name: Frontend Setup
    needs: backend-setup
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      - name: Install frontend dependencies
        run: |
          npm install
        working-directory: frontend